#!/bin/sh

# based on: https://github.com/MerryMens/AsusMerlin-WireGuard-Failover
# added args, killswitch, wan(s)/ping/dns/curl tests, logic changes, filename changes, etc

Log()
{
  echo ""; echo "====================================="
  msg=$logPrefix"$@"
  echo "=Log= $msg"
  escapedLoggerMsg=$(echo -e $msg)
  logger -c "$escapedLoggerMsg"
  echo "^^^==================^^^"
}

LogSlack()
{
  Log "$@"
  Slack "$@"
}

Slack()
{
  if [ "$logSlackPath" != "" ]; then
    escapedSlackMsg=$(echo $logPrefix"$*" | sed 's/ / /g' | sed 's/(/[/g' | sed 's/)/]/g') # replace space and brackets
    $logSlackPath $escapedSlackMsg &> /dev/null &
  fi
}

ParseArgs()
{
  fromClientConfig=$1
  shift
  echo "=== ParseArgs: fromClientConfig=$fromClientConfig $*"

  echo arg count: $#
  if [ $# -gt 1 ]; then
    unset var

    for arg in "${@:2}"; do
      echo "arg: $arg"

      if [[ ${arg:0:1} == '-' ]]; then
          if [ $arg == "--reset" ]; then
            SetDefaults
          elif [ $arg == "--disablewan1check" ]; then
            if [ $fromClientConfig -eq 0 ]; then
              echo set disableWan1Check: 1
              disableWan1Check=1
            else
              ArgCmdLineOnly $arg ""
            fi
          elif [ $arg == "--attachtorunningclient" ]; then
            if [ $fromClientConfig -eq 0 ]; then
              echo set attachToRunningClient: 1
              attachToRunningClient=1
            else
              ArgCmdLineOnly $arg ""
            fi
          elif [ $arg == "--qoneuccc" ]; then
            if [ $fromClientConfig -eq 0 ]; then
              echo set quitOnExternalAndUnmonitoredConfigChange: 1
              quitOnExternalAndUnmonitoredConfigChange=1
            else
              ArgCmdLineOnly $arg ""
            fi
          elif [ $arg == "--reload" ]; then
            echo set reloadClientConfigOnDiff: 1
            reloadClientConfigOnDiff=1
          else
            echo set var: \"$arg\"
            var=$arg
          fi
      else
          if [ -n "$var" ]; then
            # this works but spams "bad number" # if [ $arg -eq $arg ]; then
            if [ -z "${arg//[0-9]}" ]; then # this method would not recognise a negative number
              if [ $var == "-k" ]; then
                  echo set killswitch: $arg
                  killswitch=$arg
              elif [ $var == "-w" ]; then
                  echo set hsWait: $arg
                  hsWait=$arg
              elif [ $var == "-t" ]; then
                  echo set hsTimeout: $arg
                  hsTimeout=$arg
              elif [ $var == "-q" ]; then
                  echo set quitOnNoInterface: $arg
                  quitOnNoInterface=$arg
              elif [ $var == "-p" ]; then
                  echo set testPing: $arg
                  testPing=$arg
              elif [ $var == "-d" ]; then
                  echo set testDns: $arg
                  testDns=$arg
              elif [ $var == "-c" ]; then
                  echo set testCurl: $arg
                  testCurl=$arg
              elif [ $var == "-n" ]; then
                  if [ $arg -lt 1 ]; then
                    arg=1
                  fi
                  echo set logEveryNthHandshake: $arg
                  logEveryNthHandshake=$arg
              elif [ $var == "-a" ]; then
                  echo set wanWait: $arg
                  wanWait=$arg
              else
                LogSlack "unrecognised var \'$var\' - discarding that and arg \'$arg\'"
              fi
            else
              if [ $var == "--failoverconfigpath" ]; then
                if [ $fromClientConfig -eq 0 ]; then
                  echo set failoverConfigPath: $arg
                  failoverConfigPath=$arg
                else
                  ArgCmdLineOnly $var $arg
                fi
              elif [ $var == "--clientconfigdir" ]; then
                if [ $fromClientConfig -eq 0 ]; then
                  echo set clientConfigDir: $arg
                  clientConfigDir=$arg
                else
                  ArgCmdLineOnly $var $arg
                fi
              elif [ $var == "--logslackpath" ]; then
                if [ -f $arg ]; then
                  echo set logSlackPath: $arg
                  logSlackPath=$arg
                else
                  Log "logslackpath arg \'$arg\' file not found"
                fi
              elif [ $var == "-pt" ]; then
                echo set pingTargets: $arg
                pingTargets=$arg
              elif [ $var == "-dt" ]; then
                echo set nslookupTargets: $arg
                nslookupTargets=$arg
              elif [ $var == "-ct" ]; then
                echo set curlTargets: $arg
                pingTargets=$arg
              else
                LogSlack "param arg \'$arg\' for var \'$var\' is not a number - discarding both"
              fi
            fi
          else
            LogSlack "var is unset - discarding arg \'$arg\'"
          fi
          unset var
      fi
    done
    if [ -n "$var" ]; then
      LogSlack "var \'$var\' was not followed by param arg - discarded"
    fi
  fi
}

ArgCmdLineOnly()
{
  LogSlack "\'$1\' option is only valid from the command line' - discarding along with arg \'$2\'"
}

#ArgFailoverConfigOnly()
#{
#  LogSlack "\'$1\' option is only valid from within the failover config' - discarding along with arg \'$2\'"
#}

StartTimer()
{
  timerStart=$(date +%s)
}

StopTimer()
{
  return $(( $(date +%s) - $timerStart ))
}

ParamsString()
{
  # shellcheck disable=SC2028
  echo "params:\n\t\t[-k] kill switch: $killswitch\n\t\t[-w] handshake wait: $hsWait\n\t\t[-t] handshake timeout: $hsTimeout\n\t\t[-q] quit on no interface: $quitOnNoInterface\n\t\t[-p] test ping: $testPing\n\t\t[-d] test dns: $testDns\n\t\t[-c] test curl: $testCurl\n\t\t[-n] log every nth handshake: $logEveryNthHandshake\n\t\t[-a] WAN wait : $wanWait"
}

Exit()
{
  code=$1
  shift
  msg="EXITING:\n\texit code:\n\t\t$code\n\treason:\n\t\t""$@"
  if [ -n "$upSince" ]; then
    msg=$msg"\n\n\tfinal client config [$wgClientConfigFilePath], active since: $upSince\n "
  fi
  LogSlack $msg

  # negative code means show usage before exit
  if [ $code -ge 0 ]; then
    exit $code
  fi
  ShowUsage $(( $code * -1 )) # can't exit with negative code
}

# shellcheck disable=SC2329
OnTrap()
{
  sig=$?
  # why does ^C = 130?
  trap - SIGHUP SIGINT SIGQUIT SIGKILL SIGSTOP SIGABRT SIGALRM SIGFPE SIGILL SIGPIPE SIGSEGV SIGTERM SIGUSR1 SIGUSR2
  Exit 4 "trapped: $sig"
}

GetWanIfName()
{
  echo "=== GetWanIfName: $1"

  wan=""

  if [ $# -gt 0 ] && [ -z "${1//[0-9]}" ]; then
    # no arrays in sh, so longhand it is...
    if [ $1 -eq 0 ]; then
      wan=$wan0
      if [ "$wan" == "" ]; then
        wan=$(nvram get wan0_ifname)
        echo "===   wan0 was blank, fetched again: $wan"
        wan0=$wan
      fi
    elif [ $1 -eq 1 ]; then
      wan=$wan1
      if [ "$wan" == "" ]; then
        wan=$(nvram get wan1_ifname)
        echo "===   wan1 was blank, fetched again: $wan"
        wan1=$wan
      fi
    else
      echo "===   invalid wan index"
    fi
  fi

  if [ "$wan" == "" ]; then
    echo "===   blank interface name"
    return 0
  fi

  return 1
}

IsWanUp()
{
  echo "=== IsWanUp: $1"

  # check if wan is actually enabled first
  enabled=$(nvram get wan_enable)
  if [ $enabled -eq 0 ]; then
    echo "===  wan is disabled on router"
  else
    GetWanIfName $1
    if [ "$wan" != "" ]; then
      result=$(ethtool "$wan" 2>&1 | grep "Link detected:")
      echo "====   ethtool $wan: $result"
      if [ "$result" != "" ]; then
        result=`echo $result | awk '{print $3}'`
        echo "====     wan link test: $result"
        if [ "$result" == "yes" ]; then
          echo "===     wan $1 is UP"
          return 1
        fi
      fi
    fi
  fi

  echo "===   wan $1 is DOWN"
  return 0
}

WagWan()
{
  wait=$1
  echo "=== WagWan: $1"
  
  # check wan until it's up
  wanUp=0
  wasDown=0
  
  while true; do
    IsWanUp 0; wanUp=$?
    if [ $wanUp -eq 0 ]; then
      if [ $disableWan1Check -eq 0 ]; then
        # check wan1 only if wan set to failover/fallback mode ### UNTESTED ###
        wansMode=$(nvram get wans_mode)
        echo "===  wansMode: $wansMode"
        if [ "$wansMode" == "fb" ] || [ "$wansMode" == "fo" ]; then 
          IsWanUp 1; wanUp=$?
        fi
      fi
    fi

    if [ $wanUp -eq 1 ]; then
      # and we're done
      break
    fi

    if [ $wasDown -eq 0 ]; then
      wasDown=1
      wanDownSince=$(date)
      Log "CONNECTIVITY FAIL: WAN is DOWN, will silently check again every $wait seconds"
    fi

    sleep $wait
  done

  if [ $wasDown -eq 1 ]; then
    LogSlack "CONNECTIVITY RECOVERY: WAN is back UP, observed down at $wanDownSince"
  fi

  # returns 1 if was found to be down previously, in loop above
  return $wasDown
}

FindRunningClientConfig()
{
  echo "=== FindRunningClientConfig"
  runningDescr=$(nvram get "$wgc"_desc)
  echo "===  runningDescr: $runningDescr"

  clientConfigItem=0
  while read line; do
    if [ "$line" != "" ]; then
      fc=${line:0:1}
      if [ $fc  != '#' ] && [ $fc  != '-' ]; then
        clientConfigItem=$(( $clientConfigItem + 1 ))
        descr="$(echo $line | cut -d " " -f2)"
        if [ "$descr" == "$runningDescr" ]; then
          echo "===    found: $clientConfigItem"
          return $clientConfigItem
        fi
      fi
    fi
  done < "$wgFailoverConfigFilePath"
  return 0
}

DetectExternalRunningClientConfigChange()
{
  echo "=== DetectExternalRunningClientConfigChange"
  runningDescr=$(nvram get "$wgc"_desc)
  echo "===  runningDescr: $runningDescr"

  if [ "$wgClientDescription" == "$runningDescr" ]; then
    echo "===    no description change: 0"

    # check if current configs settings are the same on the router
    CompareClientConfigFile
    if [ "$compareClientConfigDiff" != "" ]; then
      printf "===    client settings \'$compareClientConfigDiff\' change on router: 3"
      return 3
    fi

    # continue with same client config
    return 0
  fi

  LogSlack "CONNECTIVITY CHANGE: the monitored client config \'$wgClientDescription\' has externally changed to \'$runningDescr\'"
  wgClientDescription=$runningDescr
  upSince=$(date) # somewhere between now and after prior handshake wait

  # is the new client config in the failover config?
  FindRunningClientConfig
  if [ $? -ne 0 ]; then
    echo "===    IN failover config: 1"

    # check if current configs settings are the same on the router
    CompareClientConfigFile
    if [ "$compareClientConfigDiff" != "" ]; then
      printf "===    client settings \'$compareClientConfigDiff\' change on router: 3(b)"
      return 3
    fi

    # continue with new config
    return 1
  fi

  if [ $reloadClientConfigOnDiff -ne 0 ]; then
    echo "===    NOT in failover config: 4"
    # will try next client config
    return 4
  fi

  echo "===    NOT in failover config: 2"
  return 2
}


readonly maxWgc=5
readonly wanUpAgainWait=15

# defaults
readonly _killswitch=1
readonly _hsWait=180
readonly _hsTimeout=300
readonly _quitOnNoInterface=0
readonly _testPing=1
readonly _testDns=1
readonly _testCurl=1
readonly _logEveryNthHandshake=10
readonly _wanWait=30
readonly _disableWan1Check=0
readonly _attachToRunningClient=0
readonly _quitOnExternalAndUnmonitoredConfigChange=0
readonly _reloadClientConfigOnDiff=0

readonly _pingTargets="8.8.8.8,1.1.1.1,9.9.9.9"
readonly _nslookupTargets="google.com,amazon.com,cloudflare.com"
readonly _curlTargets=$_nslookupTargets

readonly _alive=25
readonly _firewall=1
readonly _nat=1


SetDefaults()
{
  echo "=== SetDefaults"
  killswitch=$_killswitch
  hsWait=$_hsWait
  hsTimeout=$_hsTimeout
  quitOnNoInterface=$_quitOnNoInterface
  testPing=$_testPing
  testDns=$_testDns
  testCurl=$_testCurl
  logEveryNthHandshake=$_logEveryNthHandshake
  wanWait=$_wanWait
  disableWan1Check=$_disableWan1Check
  attachToRunningClient=$_attachToRunningClient
  quitOnExternalAndUnmonitoredConfigChange=$_quitOnExternalAndUnmonitoredConfigChange
  reloadClientConfigOnDiff=$_reloadClientConfigOnDiff

  pingTargets=$_pingTargets
  nslookupTargets=$_nslookupTargets
  curlTargets=$_curlTargets
}

ShowUsage()
{
  echo ""
  echo "Usage: wgc-failover [Client Number <1 to $maxWgc>] [Options...]"
  echo ""
  echo "   -h, --help     Show these instructions"
  echo ""
  echo " Client interface:"
  echo ""
  echo "   -k <0/1>       Enable killswitch                 (default: $_killswitch)"
  echo ""
  echo " Connectivity checks:"
  echo ""
  echo "   -w <Seconds>   Wait between handshake checks     (default: $_hsWait)"
  echo "   -t <Seconds>   Handshake timeout                 (default: $_hsTimeout)"
  echo "   -q <0/1>       Quit on interface not found       (default: $_quitOnNoInterface)"
  echo "   -p <0/1>       Test ping                         (default: $_testPing)"
  echo "   -d <0/1>       Test DNS                          (default: $_testDns)"
  echo "   -c <0/1>       Test curl                         (default: $_testCurl)"
  echo "   -n <Amount>    Log every Nth handshake           (default: $_logEveryNthHandshake)"
  echo "   -a <Seconds>   Wait between WAN checks when down (default: $_wanWait)"
  echo ""
  echo "   -pt <\"IP,...\">   Comma-separated list of IP addresses for ping test in quotes"
  echo "                        (default: \"$_pingTargets\")"
  echo "   -dt <\"URL,...\">  Comma-separated list of URLS for DNS test in quotes"
  echo "                        (default: \"$_nslookupTargets\")"
  echo "   -ct <\"URL,...\">  Comma-separated list of URLs for curl test in quotes"
  echo "                        (default: \"$_curlTargets\")"
  echo ""
  echo "   --reset        Resets any of the previous args shown above to"
  echo "                  their default values (also shown above)"
  echo ""
  echo "   --logslackpath   Path to shell script to pass priority logs to"
  echo ""
  echo "   --reload       Reload client config if its settings are modified on the router"
  echo ""
  echo " [Options...] can also be specified per client config in failover config files (on previous line)"
  echo ""
  echo "   Command line only:"
  echo ""
  echo "     --failoverconfigpath   Override the default path to the failover config"
  echo "                            (from /jffs/configs/wgc-failover-[Client Number].conf)"
  echo ""
  echo "     --clientconfigdir      Override the default configs directory path"
  echo "                            (from /jffs/configs/wgc-failover-client-[Client Number]-configs)"
  echo ""
  echo "     --disablewan1check     Don't check secondary WAN interface"
  echo ""  
  echo "     --attachtorunningclient  If the running client config description matches an"
  echo "                              entry in the failover config, then don't reload the"
  echo "                              client config but just resume monitoring it."
  echo ""
  echo "                              CAUTION: Client interface args are only applied to the"
  echo "                              client when loaded/started and will therefore not be set again."
  echo ""
  echo "     --qoneuccc     Quit on external unmonitored client config change: in other words,"
  echo "                    if the monitored client config description has changed (probably by"
  echo "                    loading a different config in the router's UI) and is not in"
  echo "                    the failover config, then byebye"
  echo ""
  echo ""
  if [ $# -eq 0 ]; then
    exit 0
  fi
  exit $1
}

##############################################################################
##############################################################################
Init()
{
  logPrefix="wgc-failover: "

  # try and keep track of unexpected terminations
  trap OnTrap SIGHUP SIGINT SIGQUIT SIGABRT SIGALRM SIGFPE SIGILL SIGPIPE SIGSEGV SIGTERM SIGUSR1 SIGUSR2

  if [ $# -eq 0 ] || [ $1 == "-h" ] || [ $1 == "--help" ]; then
    ShowUsage
  fi

  SetDefaults
  # not reset by SetDefaults
  failoverConfigPath=""
  clientConfigDir=""
  logSlackPath=""

  Log "command line: $0 $@"

  # parse args
  #   - first is client number
  echo "=== client num arg is: $1"
  if [ $1 -eq $1 ] && [ $1 -gt 0 ] && [ $1 -le $maxWgc ]; then
    echo set client num: $1
    clientNum=$1
  else
    Exit -1 "ARGUMENT FAIL: client number \'$1\' is invalid"
  fi
  wgc="wgc"$clientNum

  # fetch wan interface names
  wan0=$(nvram get wan0_ifname)
  wan1=$(nvram get wan1_ifname)

  logPrefix="wgc-failover[$clientNum]: "

  #   - optional switch/value pair args
  ParseArgs 0 $@

  # send command line to slack, if path now set
  Slack "command line: $0 $@"

  # check overridden failover config path
  if [ "$failoverConfigPath" != "" ]; then
    if ! [ -f $failoverConfigPath ]; then
      Exit 6 "ARGUMENT/FILE FAIL: failover config path \'$failoverConfigPath\' is invalid"
    fi
  fi

  # check overridden client configs dir
  if [ "$clientConfigDir" != "" ]; then
    if ! [ -d $clientConfigDir ]; then
      Exit 9 "ARGUMENT/FILE FAIL: client config dir \'$clientConfigDir\' is invalid"
    fi
  fi

  # figure out config paths

  if [ "$failoverConfigPath" != "" ]; then
    wgFailoverConfigFilePath=$failoverConfigPath
  else
    wgFailoverConfigFilePath="/jffs/configs/wgc-failover-$clientNum.conf"  

    if ! [ -f $wgFailoverConfigFilePath ]; then
      Exit 7 "FILE FAIL: failover config path \'$wgFailoverConfigFilePath\' is invalid"
    fi
  fi

  if [ "$clientConfigDir" != "" ]; then
    wgClientConfigFilesDir=$clientConfigDir
  else
    wgClientConfigFilesDir="/jffs/configs/wgc-failover-client-$clientNum-configs"

    if ! [ -d $wgClientConfigFilesDir ]; then
      Exit 10 "FILE FAIL: clients config dir \'$wgClientConfigFilesDir\' is invalid"
    fi
  fi
}

##############################################################################
Main()
{
  # wait for wan up
  WagWan 15

  # and for NTP
  WaitForNTP

  runningConfigItem=0
  clientConfigSucc=0

  # run forever
  while true
  do
    LogSlack "Loading failover config: $wgFailoverConfigFilePath"
    sleep 1

    if [ $attachToRunningClient -ne 0 ]; then
      FindRunningClientConfig
      runningConfigItem=$?
      if [ $runningConfigItem -ne 0 ]; then
        echo "=== running client config: $runningConfigItem"
      fi
    fi

    clientConfigItem=0

    # read failover config file
    while read fcline
    do
      ParseFailoverConfigLine $fcline
      ret=$?
      echo "=== ret: $ret"
      if [ $ret -eq 0 ]; then
        continue
      elif [ $ret -eq 1 ]; then
        clientConfigSucc=1
      elif [ $ret -eq 2 ]; then
        LoadAndStartClientConfig $wgClientConfigFilePath
        if [ $? -eq 0 ]; then
          # try next config instead
          LogSlack "FILE FAIL: couldn't load the client config \'$wgClientConfigFilePath\', will try next"
          continue
        fi
      fi

      # finished with this after initial client config started/attached
      attachToRunningClient=0
      runningConfigItem=0
      
      # commence monitoring client health
      lhs=0
      unset wgShow
      nhs=0

      while true
      do
        # wait on wan being up
        WagWan $wanWait
        if [ $? -eq 1 ]; then
          # was down, so wait for a bit before continuing
          Log "WAN is back UP, waiting $wanUpAgainWait seconds before continuing"
          sleep $wanUpAgainWait
        fi

        testsFailed=""
        adv=$hsWait

        wgShow=$(wg show $wgc latest-handshakes)
        echo "=== wg show $wgc latest-handshakes: $wgShow"

        ifconfig=$(ifconfig $wgc 2>&1)
        echo "=== ifconfig $wgc: $ifconfig"

        # handle interface being shutdown, possibly in router ui
        if [ "$wgShow" == "Unable to access interface: No such device" ] || [ "$ifconfig" == "ifconfig: $wgc: error fetching interface information: Device not found" ]; then
          failMsg="INTERFACE FAIL: $wgc not found"
          if [ $quitOnNoInterface -eq 0 ]; then
            LogSlack "$failMsg - expiring current client config"
            #Log "$wgClientDescription: client config active since: "$upSince
            break
          else
            Exit 3 "$failMsg (with quitOnNoInterface enabled)"
          fi
        fi

        # calc how much time passed since last handshake
        dateNow=$(date +%s);                        echo dateNow: $dateNow
        dateLhs=`echo $wgShow | awk '{print $2}'`;  echo dateLhs: $dateLhs

        # if this is blank it probably means the client is stopped
        if [ "$dateLhs" != "" ]; then
          lhs=$(( $dateNow - $dateLhs ));   echo lhs: $lhs
        else
          LogSlack "HANDSHAKE FAIL: no handshake - assuming client is stopped, switching to next client config"
          break;
        fi

        # fail if lhs is nonsense
        if [ -z $lhs ] || [ -z $dateNow ] || [ $lhs -gt 1000000000 ]; then
          LogSlack "HANDSHAKE FAIL: value is nonsense\n\t\tdateNow: $dateNow\n\t\tdateLhs: $dateLhs\n\t\tlhs: $lhs"
          testsFailed="+Handshake"
        fi

        if [ $testPing -ne 0 ]; then
          TestPing
        fi

        if [ $testDns -ne 0 ]; then
          TestDNS $dnsServer
        fi

        if [ $testCurl -ne 0 ]; then
          TestCurl
        fi

        # failures can modify next handshake wait
        if [ "$testsFailed" != "" ]; then
          if [ $adv -lt 15 ]; then
            adv=15
          fi
          LogSlack "CONNECTIVITY FAIL: [$testsFailed+], reducing next handshake wait to $adv seconds"
        fi

        nhsm=$(( $nhs % $logEveryNthHandshake ))      
        nhs=$(( $nhs + 1 ))
        if [ $nhsm -eq 0 ]; then
          Log "$wgClientDescription: handshake #$nhs was $lhs secs ago"
        fi

        # give up on this client config if out of action for too long
        if [ $lhs -ge $hsTimeout ]; then
          LogSlack "HANDSHAKE FAIL: stale value of $lhs secs >= $hsTimeout, switching to next client config"
          break
        fi

        echo "=== sleeping for $adv secs"
        sleep $adv

        # check/handle if the monitored client config has changed
        DetectExternalRunningClientConfigChange; ret=$?
        if [ $ret -eq 1 ]; then
          LogSlack "CONNECTIVITY CHANGE: Continuing to monitor the externally loaded client config"
        elif [ $ret -eq 2 ]; then
          if [ $quitOnExternalAndUnmonitoredConfigChange -eq 1 ]; then
            Exit 12 "CONNECTIVITY CHANGE: Externally loaded client config NOT in failover config - change behaviour by removing \'--qoneuccc\' arg"
          else
            LogSlack "CONNECTIVITY CHANGE: Continuing to monitor the externally loaded client config, although NOT in failover config - change behaviour by adding \'--qoneuccc\' arg"
          fi
        elif [ $ret -eq 3 ]; then
          LogSlack "CONNECTIVITY CHANGE: settings \'$compareClientConfigDiff\' changed on router from the monitored client config \'$wgClientDescription\', will reload"
          LoadAndStartClientConfig $wgClientConfigFilePath
          if [ $? -eq 0 ]; then
            LogSlack "FILE FAIL: couldn't reload the client config \'$wgClientConfigFilePath\', will try next"
            runningConfigItem=0
            break
          fi
        elif [ $ret -eq 4 ]; then
          LogSlack "CONNECTIVITY CHANGE: Externally loaded client config NOT in failover config, will try next - change behaviour by removing \'--reload\' arg"
          runningConfigItem=0
          break
        fi
        
      done
    done < "$wgFailoverConfigFilePath"

    # check client config file loaded or running one found
    if [ $clientConfigSucc -eq 0 ]; then
      Exit 11 "FILE FAIL: client config not found in \'$wgFailoverConfigFilePath\'"
    fi
  done
}
##############################################################################
##############################################################################

WaitForNTP()
{
  logged=0
  while true; do
    if [ $(nvram get ntp_ready) -ne 0 ]; then
      break
    fi
    if [ $logged -eq 0 ]; then
      Log "Wait for NTP to sync"
      logged=1
    fi
    sleep 30
  done

  if [ $logged -eq 1 ]; then
    Log "NTP sync success"
  fi
}

TestPing()
{
  echo ""; echo "============= test ping ============="

  StartTimer
  for ip in ${pingTargets//,/ }; do
    echo ""; echo "=== pinging $ip..."; echo ""
    ping -I $wgc -c 1 -w 1 $ip 2>&1
    if [ $? -eq 0 ]; then
      return
    fi
  done

  StopTimer
  adv=$(( $adv - $? ))

  testsFailed="$testsFailed+Ping"
}

TestDNS()
{
  if [ "$1" != "" ]; then
    echo ""; echo "============= test dns ============="

    StartTimer
    for domain in ${nslookupTargets//,/ }; do
      echo ""; echo "=== looking up $domain via $dnsServer..."; echo ""
      nslookup $domain $1 2>&1
      if [ $? -eq 0 ]; then
        return
      fi
    done

    StopTimer
    adv=$(( $adv - $? ))

    testsFailed="$testsFailed+DNS"
  fi
}

TestCurl()
{
  echo ""; echo "============= test curl ============="

  StartTimer
  for domain in ${curlTargets//,/ }; do
    echo ""; echo "=== curling $domain..."; echo ""
    curl -s --no-progress-meter --connect-timeout 5 --max-time 15 --interface $wgc $domain 2>&1
    if [ $? -eq 0 ]; then
      return
    fi
  done

  StopTimer
  adv=$(( $adv - $? ))

  testsFailed="$testsFailed+Curl"
  return 0
}

ParseFailoverConfigLine()
{
  line=$@
  echo "=== ParseFailoverConfigLine: $line"

  # skip blank line
  if [ "$line" == "" ]; then
    return 0
  fi

  fc=${line:0:1}
  # if line starts with # it's a comment
  if [[ $fc  == '#' ]]; then
    return 0
  fi
  # if line starts with dash then it's args
  if [[ $fc  == '-' ]]; then
    ParseArgs 1 "?" $line
    return 0
  fi

  # line is: 'filename' 'description'
  wgClientConfigFileName="$(echo $line | cut -d " " -f1)"
  wgClientDescription="$(echo $line | cut -d " " -f2)"

  # if filename starts with slash it's a full path
  fc=${wgClientConfigFileName:0:1}
  if [[ $fc  == '/' ]]; then
    wgClientConfigFilePath=$wgClientConfigFileName
    echo "=== client filename is full path: $wgClientConfigFilePath"
  else
    wgClientConfigFilePath=$wgClientConfigFilesDir/$wgClientConfigFileName
  fi

  clientConfigItem=$(( $clientConfigItem + 1 ))

  if ! [ -f $wgClientConfigFilePath ]; then
    Log "client config path \'$wgClientConfigFilePath\' is invalid"
    wgClientConfigFilePath=""
    clientConfigSucc=0
    return 0
  fi

  # check if we should attach or reload
  if [ $runningConfigItem -ne 0 ]; then
    if [ $clientConfigItem -eq $runningConfigItem ]; then

      # check if current configs settings are the same
      CompareClientConfigFile
      if [ "$compareClientConfigDiff" != "" ]; then
        LogSlack "Reloading the current runnning client config as some settings [$compareClientConfigDiff+] have been changed on the router"
        return 2
      fi

      # attach it is, then...
      LogSlack "Continuing with the current running client config: ($runningConfigItem) $wgClientDescription"
      return 1
    fi
    # try next line
    return 0
  fi

  # load this parsed client config
  return 2
}

LoadClientConfigFile()
{
  echo "=== LoadClientConfigFile"
  ParseClientConfigFile

  # set params in nvram
  nvram set "$wgc"_priv=$ccfg_priv
  nvram set "$wgc"_addr=$ccfg_addr
  nvram set "$wgc"_dns=$ccfg_dns
  nvram set "$wgc"_ppub=$ccfg_ppub
  nvram set "$wgc"_aips=$ccfg_aips
  nvram set "$wgc"_ep_addr=$ccfg_ep_addr
  nvram set "$wgc"_ep_port=$ccfg_ep_port
  nvram set "$wgc"_psk=$ccfg_psk

  nvram set "$wgc"_desc="$wgClientDescription"
  nvram set "$wgc"_alive=$_alive
  nvram set "$wgc"_enable=1
  nvram set "$wgc"_fw=$_firewall
  nvram set "$wgc"_nat=$_nat
  nvram set "$wgc"_enforce=$killswitch

  dnsServer="$ccfg_dns"
}

CompareClientConfigFile()
{
  echo "=== CompareClientConfigFile"

  compareClientConfigDiff=""
  if [ $reloadClientConfigOnDiff -ne 0 ]; then
    ParseClientConfigFile

    if [ "$(nvram get "$wgc"_priv)" != "$ccfg_priv" ]; then
      compareClientConfigDiff=$compareClientConfigDiff"+priv"
    fi
    if [ "$(nvram get "$wgc"_addr)" != "$ccfg_addr" ]; then
      compareClientConfigDiff=$compareClientConfigDiff"+addr"
    fi
    if [ "$(nvram get "$wgc"_dns)" != "$ccfg_dns" ]; then
      compareClientConfigDiff=$compareClientConfigDiff"+dns"
    fi
    if [ "$(nvram get "$wgc"_aips)" != "$ccfg_aips" ]; then
      compareClientConfigDiff=$compareClientConfigDiff"+aips"
    fi
    if [ "$(nvram get "$wgc"_ep_addr)" != "$ccfg_ep_addr" ]; then
      compareClientConfigDiff=$compareClientConfigDiff"+ep_addr"
    fi
    if [ "$(nvram get "$wgc"_ep_port)" != "$ccfg_ep_port" ]; then
      compareClientConfigDiff=$compareClientConfigDiff"+ep_port"
    fi
    if [ "$(nvram get "$wgc"_psk)" != "$ccfg_psk" ]; then
      compareClientConfigDiff=$compareClientConfigDiff"+psk"
    fi

    if [ "$(nvram get "$wgc"_alive)" != "$_alive" ]; then
      compareClientConfigDiff=$compareClientConfigDiff"+alive"
    fi
    if [ "$(nvram get "$wgc"_fw)" != "$_firewall" ]; then
      compareClientConfigDiff=$compareClientConfigDiff"+firewall"
    fi
    if [ "$(nvram get "$wgc"_nat)" != "$_nat" ]; then
      compareClientConfigDiff=$compareClientConfigDiff"+nat"
    fi
    if [ "$(nvram get "$wgc"_enforce)" != "$killswitch" ]; then
      compareClientConfigDiff=$compareClientConfigDiff"+killswitch"
    fi
  fi
}

ParseClientConfigFile()
{
  echo "=== ParseClientConfigFile"

  ccfg_priv=""
  ccfg_addr=""
  ccfg_dns=""
  ccfg_ppub=""
  ccfg_aips=""
  ccfg_ep_addr=""
  ccfg_ep_port=""
  ccfg_psk=""

  while read line
  do
    # skip blank line
    if [ "$line" == "" ]; then
      continue
    fi
    fc=${line:0:1}
    # if line starts with # it's a comment
    if [[ $fc  == '#' ]]; then
      continue
    fi
    if test "$line" != "${line%" = "*}" # remove spaces around equal sign to make formatting easy
    then
      lineFormatted="${line//" "/""}"
      if test "$lineFormatted" != "${lineFormatted%"PrivateKey"*}"; then
        ccfg_priv="${lineFormatted#*=}"
      elif test "$lineFormatted" != "${lineFormatted%"Address"*}"; then
        ccfg_addr="${lineFormatted#*=}"
      elif test "$lineFormatted" != "${lineFormatted%"DNS"*}"; then
        ccfg_dns="${lineFormatted#*=}"
      elif test "$lineFormatted" != "${lineFormatted%"PublicKey"*}"; then
        ccfg_ppub="${lineFormatted#*=}"
      elif test "$lineFormatted" != "${lineFormatted%"AllowedIPs"*}"; then
        ccfg_aips="${lineFormatted#*=}"
      elif test "$lineFormatted" != "${lineFormatted%"Endpoint"*}"; then
        endpointFull="${lineFormatted#*=}"
        ccfg_ep_addr="${endpointFull%:*}"
        ccfg_ep_port="${endpointFull#*:}"
      elif test "$lineFormatted" != "${lineFormatted%"PresharedKey"*}"; then
        ccfg_psk="${lineFormatted#*=}"
      fi
    fi
  done < "$wgClientConfigFilePath"
}

LoadAndStartClientConfig()
{
  path=$1
  echo "LoadAndStartClientConfig: $path"

  if ! [ -f $path ]; then
    LogSlack "FILE FAIL: client config path \'$wgClientConfigFilePath\' is invalid - trying next"
    wgClientConfigFilePath=""
    clientConfigSucc=0
    return 0
  fi

  wgClientConfigFilePath=$path

  if [ -n "$upSince" ]; then
    LogSlack "Previous client config was active since: $upSince"
    unset upSince
  fi

  LogSlack "Loading client config $wgClientConfigFilePath as $wgClientDescription\n\t"$(ParamsString)

  # stop client before changing client settings in nvram
  service "stop_wgc $clientNum"
  sleep 3

  # read client config file into variables and generate nvram set commands
  dnsServer=""
  LoadClientConfigFile
  clientConfigSucc=1
  
  # start client
  service "start_wgc $clientNum"
  upSince=$(date)
  sleep 3

  return 1
}

##############################################################################
# entry point
##############################################################################

#logPrefix="test"
#logSlackPath="/jffs/scripts/mh/sendToSlack.sh"

#LogSlack 1 2 3 4 
#LogSlack "\t\t\n4\n\t\t\n5\t\t\n6"

#exit 0



Init $@
Main
Exit 5 "eof"
##############################################################################
##############################################################################