#!/bin/sh

# expire a running failover client config

maxWgc=5

if [ $1 -eq $1 ] && [ $1 -gt 0 ] && [ $1 -le $maxWgc ]; then
    clientNum=$1
else
    Exit -1 "ARGUMENT FAIL: client number \'$1\' is invalid"
fi
wgc="wgc"$clientNum

# this relied on wgc-failover --reload switch
#descr=$(nvram get "$wgc"_desc)
#descr="#$descr"
#nvram set "$wgc"_desc=$descr

# new: this file checked at every handshake
touch "/tmp/wgc-failover-expire-"$clientNum
