[Interface]
PrivateKey = kasjlkajkjlkajslksjalkjslkjaklsjaklasjslkjsal
Address = 172.1.23.45/32
# if DNS server not specified here then wgc-failover will not perform DNS tests
DNS = 10.1.2.3 

[Peer]
PublicKey = jlkdsjdjlskjdlksjdlkjslkdjlksjdlkjslkdjlksjdlkjs
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = cz.examplevpnserver.com:12345
