# you can add comments in here, prefixed with '#'
# blank lines are fine, too

# client config filename    friendly name
FO_ExampleVPN-cz.conf       FO_ExampleVPN-cz

# and args (run /jffs/scripts/wgc-failover --help for full list):
-k 1 -w 123
# specify full file path, if that floats your boat:
/path/to/FO_ExampleVPN-fi.conf  FO_ExampleVPN-fi

-k 0 -w 234 -d 0
FO_ExampleVPN-se.conf       FO_ExampleVPN-se
